<!-- code/Leron.Audio.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Leron.Audio</RootNamespace>
    <AssemblyName>Leron.Audio</AssemblyName>
    <Version>0.1.0</Version>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <!-- CA1416 подавлен, так как WPF и так работает только на Windows -->
    <NoWarn>NU1701;CA1416</NoWarn>
    <ApplicationIcon Condition="Exists('Assets/icon.ico')">Assets/icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup Condition="Exists('Assets/icon.ico')">
    <Resource Include="Assets/icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NHotkey.Wpf" Version="3.0.0" />
    <PackageReference Include="InputSimulatorPlus" Version="1.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Whisper.net" Version="1.9.2-preview1" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.9.2-preview1" />
    <PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.9.2-preview1" />
    <PackageReference Include="Whisper.net.Runtime.Cuda" Version="1.9.2-preview1" />
  </ItemGroup>
</Project>